// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/barnettt/banking/domain (interfaces: CustomerRepository)

// Package domain is a generated GoMock package.
package domain

import (
	reflect "reflect"

	exceptions "github.com/barnettt/banking-lib/exceptions"
	domain "github.com/barnettt/banking/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockCustomerRepository is a mock of CustomerRepository interface.
type MockCustomerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerRepositoryMockRecorder
}

// MockCustomerRepositoryMockRecorder is the mock recorder for MockCustomerRepository.
type MockCustomerRepositoryMockRecorder struct {
	mock *MockCustomerRepository
}

// NewMockCustomerRepository creates a new mock instance.
func NewMockCustomerRepository(ctrl *gomock.Controller) *MockCustomerRepository {
	mock := &MockCustomerRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerRepository) EXPECT() *MockCustomerRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockCustomerRepository) FindAll() ([]domain.Customer, *exceptions.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]domain.Customer)
	ret1, _ := ret[1].(*exceptions.AppError)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCustomerRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCustomerRepository)(nil).FindAll))
}

// FindById mocks base method.
func (m *MockCustomerRepository) FindById(arg0 string) (*domain.Customer, *exceptions.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", arg0)
	ret0, _ := ret[0].(*domain.Customer)
	ret1, _ := ret[1].(*exceptions.AppError)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockCustomerRepositoryMockRecorder) FindById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockCustomerRepository)(nil).FindById), arg0)
}

// FindByStatus mocks base method.
func (m *MockCustomerRepository) FindByStatus(arg0 string) ([]domain.Customer, *exceptions.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", arg0)
	ret0, _ := ret[0].([]domain.Customer)
	ret1, _ := ret[1].(*exceptions.AppError)
	return ret0, ret1
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockCustomerRepositoryMockRecorder) FindByStatus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockCustomerRepository)(nil).FindByStatus), arg0)
}
