// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/barnettt/banking/service (interfaces: TransactionService)

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	exceptions "github.com/barnettt/banking-lib/exceptions"
	dto "github.com/barnettt/banking/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockTransactionService is a mock of TransactionService interface.
type MockTransactionService struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionServiceMockRecorder
}

// MockTransactionServiceMockRecorder is the mock recorder for MockTransactionService.
type MockTransactionServiceMockRecorder struct {
	mock *MockTransactionService
}

// NewMockTransactionService creates a new mock instance.
func NewMockTransactionService(ctrl *gomock.Controller) *MockTransactionService {
	mock := &MockTransactionService{ctrl: ctrl}
	mock.recorder = &MockTransactionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionService) EXPECT() *MockTransactionServiceMockRecorder {
	return m.recorder
}

// NewTransaction mocks base method.
func (m *MockTransactionService) NewTransaction(arg0 *dto.TransactionRequest) (*dto.TransactionResponse, *exceptions.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTransaction", arg0)
	ret0, _ := ret[0].(*dto.TransactionResponse)
	ret1, _ := ret[1].(*exceptions.AppError)
	return ret0, ret1
}

// NewTransaction indicates an expected call of NewTransaction.
func (mr *MockTransactionServiceMockRecorder) NewTransaction(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTransaction", reflect.TypeOf((*MockTransactionService)(nil).NewTransaction), arg0)
}
